export const BASE_URL = 'https://vbase-api.vercel.app/'
export const API_URL = BASE_URL // + 'api/'
export const IMAGEGAME_URL = '/static/images/games/gameplay/'
export const IMAGEINFO_URL = '/static/images/addons/'
export const ITEMS_PER_PAGE = 20
export const DOCUMENT_TITLE = 'VBase'
export const DOCUMENT_TITLE_SEPARATOR = '-'
export const MAX_REVIEW_LENGTH = 2000

export const RESULTS = {
  REQUESTED: 'RESULTS_REQUESTED',
  RETRIEVED: 'RESULTS_RETRIEVED',
  FAILED: 'RESULTS_FAILED',
  PAGEREQUESTED: 'RESULTS_PAGEREQUESTED'
}

export const CONTACT = {
  SUBMITTED: 'CONTACT_SUBMITTED',
  FAILED: 'CONTACT_FAILED',
  SENTSUCCESFULLY: 'CONTACT_SENTSUCCESFULLY'
}

export const GAME = {
  REQUESTEDINFO: 'GAME_REQUESTEDINFO',
  FAILEDONURL: 'GAME_FAILEDONURL',
  FAILEDLOADING: 'GAME_FAILEDLOADING',
  INFORETRIEVED: 'GAME_INFORETRIEVED',
  RELATEDGAMESRETRIEVED: 'GAME_RELATEDGAMESRETRIEVED',
  CHANGEIMAGEREQUESTED: 'GAME_CHANGEIMAGEREQUESTED'
}

export const INFO = {
  CONTENTREQUESTED: 'INFO_CONTENTREQUESTED',
  FAILEDLOADING: 'INFO_FAILEDLOADING',
  CONTENTRETRIEVED: 'INFO_CONTENTRETRIEVED'
}

export const USERINPUT = {
  LISTREQUESTED: 'USERINPUT_LISTREQUESTED',
  LISTRETRIEVED: 'USERINPUT_LISTRETRIEVED',
  LISTFAILED: 'USERINPUT_LISTFAILED',
  SUBMITTED: 'USERINPUT_SUBMITTED',
  ACCEPTED: 'USERINPUT_ACCEPTED',
  SENDFAILED: 'USERINPUT_SENDFAILED'
}
